name: Build Installers

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

concurrency:
  # SHA is added to the end if on `main` to let all main workflows run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ github.ref == 'refs/heads/main' && github.sha || '' }}
  cancel-in-progress: true

jobs:
  build_mac:
    name: Build Mac Installer
    runs-on: macos-latest
    steps:
      - uses: Chia-Network/actions/clean-workspace@main

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node 16.x
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16.x'

      - name: npm install
        run: |
          node --version
          npm install

      - name: Import Apple installer signing certificate
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_DEV_ID_APP }}
          p12-password: ${{ secrets.APPLE_DEV_ID_APP_PASS }}

      - name: Build electron app
        run: npm run electron:package:mac

      - name: Upload Mac Installer
        uses: actions/upload-artifact@v2
        with:
          name: mac-installer
          path: ${{ github.workspace }}/dist/*.dmg
