name: Build & Release

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

concurrency:
  # SHA is added to the end if on `main` to let all main workflows run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ github.ref == 'refs/heads/main' && github.sha || '' }}
  cancel-in-progress: true

jobs:
  build_mac:
    name: Build Mac Installer
    runs-on: macos-latest
    steps:
      - uses: Chia-Network/actions/clean-workspace@main

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: install dmg-license
        run: npm i dmg-license

      - name: npm install
        run: |
          node --version
          npm install

      - name: Import Apple installer signing certificate
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_DEV_ID_APP }}
          p12-password: ${{ secrets.APPLE_DEV_ID_APP_PASS }}

      - name: Build electron app
        env:
          CSC_FOR_PULL_REQUEST: "true"
        run: npm run electron:package:mac

      - name: Notarize
        run: |
          DMG_FILE=$(find ${{ github.workspace }}/dist/ -type f -name '*.dmg')
          npm install -g notarize-cli
          notarize-cli \
            --file="$DMG_FILE" \
            --bundle-id net.chia.cadt-ui \
            --username "${{ secrets.APPLE_NOTARIZE_USERNAME }}" \
            --password "${{ secrets.APPLE_NOTARIZE_PASSWORD }}"

      - name: Upload Mac Installer
        uses: actions/upload-artifact@v3
        with:
          name: cadt-ui-mac-installer
          path: ${{ github.workspace }}/dist/*.dmg

  build_windows:
    name: Build Windows Installer
    runs-on: windows-2019
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: npm install
        run: |
          node --version
          npm install

      - name: Build electron app
        env:
          CSC_LINK: ${{ secrets.WIN_CODE_SIGN_CERT }}
          CSC_KEY_PASSWORD: ${{ secrets.WIN_CODE_SIGN_PASSWORD }}
        run: npm run electron:package:win

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v3
        with:
          name: cadt-ui-windows-installer
          path: ${{ github.workspace }}/dist/*.exe

  build_linux:
    name: Build Linux Installer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: npm install
        run: |
          node --version
          npm install

      - name: Build electron app
        run: npm run electron:package:linux

      - name: Upload Linux Installer
        uses: actions/upload-artifact@v3
        with:
          name: cadt-ui-linux-installer
          path: ${{ github.workspace }}/dist/*.deb

  build_web:
    name: Build Climate Warehouse Web App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: npm install and build
        run: |
          node --version
          npm install
          npm run build

      - name: Create .tar.gz of the web build
        run: tar -cvzf cadt-ui-web-build.tar.gz build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: cadt-ui-web-build
          path: cadt-ui-web-build.tar.gz

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build_mac
      - build_windows
      - build_linux
      - build_web
    steps:
      - name: Download Windows artifacts
        uses: actions/download-artifact@v3
        with:
          name: cadt-ui-windows-installer
          path: cadt-ui-windows-installer

      - name: Download MacOS artifacts
        uses: actions/download-artifact@v3
        with:
          name: cadt-ui-mac-installer
          path: cadt-ui-mac-installer

      - name: Download Linux artifacts
        uses: actions/download-artifact@v3
        with:
          name: cadt-ui-linux-installer
          path: cadt-ui-linux-installer

      - name: Download Web artifact
        uses: actions/download-artifact@v3
        with:
          name: cadt-ui-web-build
          path: cadt-ui-web-build

      - name: Get Filenames
        run: |
          DMG_FILE=$(find ${{ github.workspace }}/cadt-ui-mac-installer/ -type f -name '*.dmg')
          DEB_FILE=$(find ${{ github.workspace }}/cadt-ui-linux-installer/ -type f -name '*.deb')
          EXE_FILE=$(find ${{ github.workspace }}/cadt-ui-windows-installer/ -type f -name '*.exe')
          WEB_FILE=$(find ${{ github.workspace }}/cadt-ui-web-build/ -type f -name '*.tar.gz')

          echo "DMG_FILE=$DMG_FILE" >>$GITHUB_ENV
          echo "DEB_FILE=$DEB_FILE" >>$GITHUB_ENV
          echo "EXE_FILE=$EXE_FILE" >>$GITHUB_ENV
          echo "WEB_FILE=$WEB_FILE" >>$GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            ${{ env.DMG_FILE }}
            ${{ env.DEB_FILE }}
            ${{ env.EXE_FILE }}
            ${{ env.WEB_FILE }}
